WIP: `Alphabet`, `Word`
kalmarek/CGT_UniHeidelberg_2022 pull request #11
Opened 2022-06-26 21:36 UTC by fvanmaele

Work towards Exercise 1 and Exercise 2 of `05_Alphabets_and_words.jl` you sent us.

- [x] Exercise 1 - Alphabets (`src/alphabet.jl`)
   - [x] `struct Alphabet{T}`
   - [x] Iterator interface (`Base.iterate`, `Base.length`)
   - [x] Indexing (`Base.getindex` for `Integer` and `letter:T`)
   - [x] Inverses (`hasinverse`, `setinverse!`, `Base.inv`)
   - [x] I/O (`Base.show` taken from the worksheet)
   - [x] Tests (`test/alphabet.jl`)
- [ ] Exercise 2 - Words (`src/word.jl`)
   - [x] `struct Word{T}` with default `UInt8` storage
   - [x] `AbstractVector` interface (`Base.size`, `Base.getindex`, `Base.setindex!`)
   - [x] Iterator interface (`Base.iterate`, `Base.length`)
   - [x] Multiplication (`Base.:*`), identity (`Base.one`)
   - [x] Inverses (`inv!` taken from worksheet, `Base.similar`)
   - [ ] I/O (`Base.show` taken from worksheet, `string_repr` has an error)
   - [x] `SubWord` with `@view`
   - [ ] `BufferWord`
   - [ ] Tests (`tests/word.jl`)

- [ ] Exercise 3 - Free groups
   - [ ] `FreeGroup`
   - [ ] `FPGroupElem`
   - [ ] Multiplication
   - [ ] Inversion
   - [ ] Solve the word problem
   - [ ] Tests

I've also implemented `Base.startswith` and `Base.occursin` for `Word`, as it seems they might become useful later on (small cancellation?). 

`Word` compiles, but there are no tests for it yet (I wrote some for `Alphabet`). I haven't started work on `FreeGroup` and `FPGroupElem` yet.

2022-07-11 22:30 UTC, kalmarek requested changes

2022-07-11 22:30 UTC, kalmarek commented on src/word.jl
> +Base.pop!(w::Word) = pop!(w.letter_indices)
yes, these methods will be very important soon:
```julia
Base.popfirst!
Base.prepend!
```
Later also `push!`, `pushfirst!`, `pop!`, `append!` etc. It's nice to have them collected

2022-07-11 22:30 UTC, kalmarek commented on src/word.jl
> +            if (l1 == inv(l2)) || (l2 == inv(l1))
this is never satisfied as `inv` should contain `A`

2022-07-11 22:30 UTC, kalmarek commented on src/free_group.jl
> +#   once for each multiplication) instead of 2;
:+1:

2022-07-11 22:30 UTC, kalmarek commented on src/free_group.jl
> +abstract type AbstractFreeGroup{T} end
this should be `AbstractFPGroup{T, W}` probably
`T` is the type of the letters in an `Alphabet`, `W` is the default type of the `Word`s for storage.

2022-07-11 22:30 UTC, kalmarek commented on src/free_group.jl
> +mutable struct FPGroupElement{W<:AbstractWord, G<:AbstractFreeGroup} <: GroupElement
from usability perspective `G should come first and `W` afterwards (this is only about the ease of writing code)

2022-07-11 22:30 UTC, kalmarek commented on src/free_group.jl
> +end
see my comments about `similar` for `Word`s

2022-07-11 22:30 UTC, kalmarek commented on src/free_group.jl
> +    @assert g.parent === h.parent
It's better to define accessors
`Base.parent(g::FPGroupElement) = g.parent`
`word(g::FPGroupElement) = g.word`

However in the latter it's a bit problematic since here we would be relying on `word` returning a mutable object bound to `g`, so it's hardly an abstraction. From the mathematical perspective it actually does read better though, so that'd be my recommendation.

2022-07-11 22:30 UTC, kalmarek commented on src/free_group.jl
> +end
note that `reduce` always allocated a new `Word`. As perf. it'd be nicer to check here if the word is reducible and descend to `reduce` only in this case.

btw. whenever you see `g.parent.A` it means that we need better abstractions:
```julia
G = parent(g)
reduce(alphabet(A), word(g))
```
or even better, first define
```julia
reduce(G::FreeGroup, g::FPGroupElement) = reduce(alphabet(G), word(g))
```
then just use it as:
```julia
g.word = reduce(parent(G), word(g))
```
this probably should tell you that the initial reduction should have been modifying as well, but we will see in this week how to achieve it ;)

2022-07-11 22:30 UTC, kalmarek commented on src/free_group.jl
> +end
in general `*` should be as simple as possible: allocate the result, call some form of mutating `mul!` on words, wrap the result in `FPGroupElement` and return.

```julia
function Base.:*(g::FPGroupElement, h::FPGroupElement)
    @assert parent(g) === parent(h)
    out = similar(g, length(word(g)) + length(word(h)))
    out = mul!(out, word(g), word(h))
    return FPGroupElement(out, parent(g))
end
```

reduction (as an expensive operation) should be only done lazily/when necessary, i.e. when printing (for our well-being), solving the word problem, hashing etc.

2022-07-11 22:30 UTC, kalmarek commented on src/free_group.jl
> +end
:+1:

2022-07-11 22:30 UTC, kalmarek commented on test/word.jl
> +        @test one(W1).letter_indices == []
these tests depend on the internal representation of `Word` so these need to be kept in sync with the struct.
It'd be better to ask if
```julia
@test collect(W11) == [collect(W1); collect(W1)]
@test W11 == repeat(W1, 2) # this guy is a `Word`!
@test isempty(one(W1))
```

2022-07-13 10:54 UTC, kalmarek commented on src/word.jl
> +end
I just checked this and doesn't work due to method ambiguity; Let's leave those as they are;

2022-07-23 11:09 UTC, fvanmaele commented on src/word.jl
> +            if (l1 == inv(l2)) || (l2 == inv(l1))
I have no idea why this worked in the first place...

2022-07-23 11:19 UTC, fvanmaele commented on src/free_group.jl
> +abstract type AbstractFreeGroup{T} end
I've changed it to:
```julia
abstract type AbstractFPGroup{T, W} end

struct FreeGroup{T, W} <: AbstractFPGroup{T, W}
    A::Alphabet{T}
    gens::Vector{W} # stores `Word`s
end
```
I think we also discussed in class on the possiblity to store `FPGroupElement`s in `gens`?

2022-07-23 12:32 UTC, fvanmaele commented
I've tried to address as many points as possible. The tests for `FreeGroup` and `FPGroupElement` are still missing, however.

2022-07-24 20:12 UTC, fvanmaele commented
I've imported the remaining methods from `notebooks/06_Rewriting.jl` and rebased everything. Now it's 5 commits, down from 42 :)

2022-07-26 18:33 UTC, kalmarek commented on src/free_group.jl
> +end
we could replace those by a single
```julia
Base.similar(g::FPGroupElement, n=length(word(g))) = FPGroupElement(parent(g), similar(word(g), n))
```

2022-07-26 18:36 UTC, kalmarek approved these changes

2022-07-27 12:19 UTC, fvanmaele commented on src/free_group.jl
> +end
Done

2022-07-29 10:15 UTC, kalmarek commented
@fvanmaele @JannisHeising I'm happy to merge this is here unless there are some objections;)

Note: If there is some code depending on what was here it will need to be rebased, please don't just copy&paste code from file to file ;)

2022-07-31 10:48 UTC, fvanmaele commented
Works for me!

2022-08-01 09:40 UTC, merged