`Permutation`, `CyclePermutation`
kalmarek/CGT_UniHeidelberg_2022 pull request #2
Opened 2022-04-30 17:54 UTC by fvanmaele

This PR implements #1, ii.e. the `Permutation` and `CyclePermutation` classes as implementation of `AbstractPermutation`. 

`Permutation` is as in the lecture. I chose the implementation for `CyclePermutation` as follows:

**Constructor**
* `CyclePermutation` stores both the cycles (from `cycle_decomposition()`) and the images (from the constructor argument). This is done so that `σ(i)` is done as an array read with `O(1)` complexity, instead of having to find the cycle which contains the index `i` (which I believe is `O(n)` because cycles are not necessarily sorted).
* When decomposing a permutation into cycles, the cycles are not necessarily disjoint. That said, I believe `cycle_decomposition()` does return disjoint cycles, by computing group orbits (which are either disjoint or identical) and a `visible` mask. I've encoded this assumption in an additional class invariant, which is verified if `check=true`.

**Operations**
* The implementation of `(σ::CyclePermutation)(i)` matches the one of `(σ::Permutation)(i)`, because `CyclePermutation` stores the cycles and images by the above.
  - **Q**: `CyclePermutation` is not a subtype of `Permutation`, so I assume something like `(σ::CyclePermutation)(i) = (σ::Permutation)(i)` is not possible. If so (and the function body were complex enough to make this worthwhile), a "detail" function could be created that's called by both `(σ::CyclePermutation)(i)` and `(σ::CyclePermutation)(i)`.
* `degree` is implemented by finding the highest index for each cycle, then taking the maximum over those. This should also work with the identity (`deg = 1` in the beginning) and cycles of length 1.
* `cycle_decomposition` is defined for any `AbstractPermutation`. However, in the case of a `CyclePermutation` the computations would be redundant, since a cycle decomposition is already known (and is stored in the object). Therefore I've added a specialization that returns `σ.cycles`.

Exercise 2 is still a work-in-progress. I've looked at `Expr`, `Symbol`, `Meta.parse` and written some tests for a later `perm"..."` implementation.

----
There is one outstanding issue I have with Exercise 1: I can't figure out how to actually run the code! When running the tests as described in issue #1, or through `julia --project=$PWD test/runtests.jl`, I get a long stacktrace:
```julia
Test Summary: |
CGT           | No tests
ERROR: LoadError: MethodError: no method matching degree(::Permutation)
Stacktrace:
  [1] cycle_decomposition(σ::Permutation)
    @ CGT_UniHeidelberg_2022.AbstractPermutations ~/source/repos/CGT_UniHeidelberg_2022/src/AbstractPermutations.jl:92
  [2] show(io::IOContext{IOBuffer}, σ::Permutation)
    @ CGT_UniHeidelberg_2022.AbstractPermutations ~/source/repos/CGT_UniHeidelberg_2022/src/AbstractPermutations.jl:76
  [3] show_delim_array(io::IOContext{IOBuffer}, itr::Tuple{Permutation}, op::Char, delim::Char, cl::Char, delim_one::Bool, i1::Int64, n::Int64)
    @ Base ./show.jl:1244
  [4] show_delim_array
    @ ./show.jl:1229 [inlined]
  [5] show(io::IOContext{IOBuffer}, t::Tuple{Permutation})
    @ Base ./show.jl:1262
  [6] _show_default(io::IOContext{IOBuffer}, x::Any)
    @ Base ./show.jl:413
  [7] show_default
    @ ./show.jl:396 [inlined]
  [8] show(io::IOContext{IOBuffer}, x::Any)
    @ Base ./show.jl:391
  [9] _show_default(io::IOContext{IOBuffer}, x::Any)
    @ Base ./show.jl:413
 [10] show_default
    @ ./show.jl:396 [inlined]
 [11] show(io::IOContext{IOBuffer}, x::Any)
    @ Base ./show.jl:391
 [12] sprint(f::Function, args::LoadError; context::Pair{Symbol, Bool}, sizehint::Int64)
    @ Base ./strings/io.jl:112
 [13] Test.Error(test_type::Any, orig_expr::Any, value::Any, bt::Any, source::Any)
    @ Test ~/packages/julias/julia-1.7/share/julia/stdlib/v1.7/Test/src/Test.jl:174
 [14] macro expansion
    @ ~/packages/julias/julia-1.7/share/julia/stdlib/v1.7/Test/src/Test.jl:1289 [inlined]
 [15] top-level scope
    @ ~/source/repos/CGT_UniHeidelberg_2022/test/runtests.jl:5
in expression starting at /home/fvanmaele/source/repos/CGT_UniHeidelberg_2022/test/runtests.jl:4

caused by: LoadError: MethodError: no method matching degree(::Permutation)
Stacktrace:
  [1] cycle_decomposition(σ::Permutation)
    @ CGT_UniHeidelberg_2022.AbstractPermutations ~/source/repos/CGT_UniHeidelberg_2022/src/AbstractPermutations.jl:92
  [2] show(io::IOContext{IOBuffer}, σ::Permutation)
    @ CGT_UniHeidelberg_2022.AbstractPermutations ~/source/repos/CGT_UniHeidelberg_2022/src/AbstractPermutations.jl:76
  [3] show_delim_array(io::IOContext{IOBuffer}, itr::Tuple{Permutation}, op::Char, delim::Char, cl::Char, delim_one::Bool, i1::Int64, n::Int64)
    @ Base ./show.jl:1244
  [4] show_delim_array
    @ ./show.jl:1229 [inlined]
  [5] show(io::IOContext{IOBuffer}, t::Tuple{Permutation})
    @ Base ./show.jl:1262
  [6] _show_default(io::IOContext{IOBuffer}, x::Any)
    @ Base ./show.jl:413
  [7] show_default
    @ ./show.jl:396 [inlined]
  [8] show(io::IOContext{IOBuffer}, x::Any)
    @ Base ./show.jl:391
  [9] sprint(f::Function, args::MethodError; context::Pair{Symbol, Bool}, sizehint::Int64)
    @ Base ./strings/io.jl:112
 [10] Test.Error(test_type::Any, orig_expr::Any, value::Any, bt::Any, source::Any)
    @ Test ~/packages/julias/julia-1.7/share/julia/stdlib/v1.7/Test/src/Test.jl:174
 [11] macro expansion
    @ ~/packages/julias/julia-1.7/share/julia/stdlib/v1.7/Test/src/Test.jl:1289 [inlined]
 [12] top-level scope
    @ ~/source/repos/CGT_UniHeidelberg_2022/test/permutations.jl:2
 [13] include(fname::String)
    @ Base.MainInclude ./client.jl:451
 [14] macro expansion
    @ ~/source/repos/CGT_UniHeidelberg_2022/test/runtests.jl:5 [inlined]
 [15] macro expansion
    @ ~/packages/julias/julia-1.7/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
 [16] top-level scope
    @ ~/source/repos/CGT_UniHeidelberg_2022/test/runtests.jl:5
in expression starting at /home/fvanmaele/source/repos/CGT_UniHeidelberg_2022/test/permutations.jl:1

caused by: MethodError: no method matching degree(::Permutation)
Stacktrace:
  [1] cycle_decomposition(σ::Permutation)
    @ CGT_UniHeidelberg_2022.AbstractPermutations ~/source/repos/CGT_UniHeidelberg_2022/src/AbstractPermutations.jl:92
  [2] show(io::IOContext{IOBuffer}, σ::Permutation)
    @ CGT_UniHeidelberg_2022.AbstractPermutations ~/source/repos/CGT_UniHeidelberg_2022/src/AbstractPermutations.jl:76
  [3] show_delim_array(io::IOContext{IOBuffer}, itr::Tuple{Permutation}, op::Char, delim::Char, cl::Char, delim_one::Bool, i1::Int64, n::Int64)
    @ Base ./show.jl:1244
  [4] show_delim_array
    @ ./show.jl:1229 [inlined]
  [5] show(io::IOContext{IOBuffer}, t::Tuple{Permutation})
    @ Base ./show.jl:1262
  [6] _show_default(io::IOContext{IOBuffer}, x::Any)
    @ Base ./show.jl:413
  [7] show_default
    @ ./show.jl:396 [inlined]
  [8] show(io::IOContext{IOBuffer}, x::Any)
    @ Base ./show.jl:391
  [9] sprint(f::Function, args::MethodError; context::Pair{Symbol, Bool}, sizehint::Int64)
    @ Base ./strings/io.jl:112
 [10] Test.Error(test_type::Any, orig_expr::Any, value::Any, bt::Any, source::Any)
    @ Test ~/packages/julias/julia-1.7/share/julia/stdlib/v1.7/Test/src/Test.jl:174
 [11] do_test(result::Test.ExecutionResult, orig_expr::Any)
    @ Test ~/packages/julias/julia-1.7/share/julia/stdlib/v1.7/Test/src/Test.jl:634
 [12] macro expansion
    @ ~/packages/julias/julia-1.7/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [13] macro expansion
    @ ~/source/repos/CGT_UniHeidelberg_2022/test/permutations.jl:7 [inlined]
 [14] macro expansion
    @ ~/packages/julias/julia-1.7/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
 [15] top-level scope
    @ ~/source/repos/CGT_UniHeidelberg_2022/test/permutations.jl:2
 [16] include(fname::String)
    @ Base.MainInclude ./client.jl:451
 [17] macro expansion
    @ ~/source/repos/CGT_UniHeidelberg_2022/test/runtests.jl:5 [inlined]
 [18] macro expansion
    @ ~/packages/julias/julia-1.7/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
 [19] top-level [...]

2022-05-01 18:34 UTC, fvanmaele commented
The issue was that I needed to `import` `..degree` and `..cycle_decomposition`.

----
**Exercise 2** is now also implemented. I've come up with two ways:
1. regexp and `eachmatch()`: first match a pattern over the cycles, then over the numbers in each cycle. This approach has the issue that no input validation is done: anything matching a cycle is returned.
2. writing a FSE by hand. This is pretty tedious but does input validation and gives detailed error messages.
   * I've tested this using invalid inputs, but I couldn't get `@test_throws` to work. All the (commented) test cases in `test/permutation.jl` throw however as expected.

In the latter case, I've used Julia expressions with `Expr`, implemented as an overload of `Meta.parse`. The expression is then evaluated with `eval` in `@perm_str`. Note that each cycle is converted to `images` before turning it into an expression: this allows reuse of `*` defined for `AbstractPermutation` (and in particular, its convention of acting on the right).

There was also a question in **Exercise 1**, about the behavior when multiplying `CyclePermutation` and `Permutation`. All I can think of is that this would be not type stable, in the sense that the output type depends on the order of the arguments. 

That is, given the signature
```julia
Base.:(*)(σ::P, τ::AbstractPermutation) where P<:AbstractPermutation
```
and the inputs
```
σ = CyclePermutation([2,1])
τ = Permutation([1,2,4,3])
```
we have `σ*τ = τ*σ` because these are disjoint cycles, but the output type differs:
```
julia> typeof(τ*σ)
Permutation
julia> typeof(σ*τ)
CyclePermutation
```
I believe this follows from the fact that the constructor of `P` (the type of the first argument) is taken: in `Base.:(*)`
```julia
return P(img, false)
```

2022-05-01 21:21 UTC, kalmarek requested changes

2022-05-01 21:21 UTC, kalmarek commented on src/permutations.jl
> +    return deg
common pattern here is to use `mapreduce`. Can you work out how to do it here?

2022-05-01 21:21 UTC, kalmarek commented on src/permutations.jl
> +function cycle_decomposition(σ::CyclePermutation)
If we don't export `cycle_decomposition` then here we need to write
```julia
function AbstractPermutations.cycle_decomposition(σ::CyclePermutation)`
    ...
end
```

2022-05-01 21:21 UTC, kalmarek commented on src/permutations.jl
> +end
That's definitely good enough ;)

2022-05-01 21:21 UTC, kalmarek commented on src/permutations.jl
> +    deg = max(cycle...)
there is also a function `maximum` that finds maximum of a collection

2022-05-01 21:21 UTC, kalmarek commented on src/permutations.jl
> +# P<:AbstractPermutation results in `UndefVarError: P not defined`.
It's very good that you tried ;) we can discuss it in class

2022-05-01 21:21 UTC, kalmarek commented on test/permutations.jl
> +# (cf. TEMPLATE_TEST_CASE in Catch2)
have a look at the docstring of `@testset` from module `Test`

2022-05-01 21:21 UTC, kalmarek commented on test/permutations.jl
> +    # @test_throws Meta.ParseError perm"(2,3,1)⋅(4,5)" # this or (2,3,1)∗(4,5) is arguably also a valid case
I'm not sure if I get correctly what behaviour are you referring to, but this may be because macros are evaluated during source parsing and only then `@test_throws` would be evaluated. Here the error is thrown before tests are even run.

One way of testing this is to test `string_to_cycles` directly.

2022-05-01 21:21 UTC, kalmarek commented on src/permutations.jl
> +    return eval(Meta.parse(Permutation, str))
`macro`s are a way of transforming one piece of code to another piece of code. to quote its docstring
> Macros are a way to run generated code without calling `eval`, since the generated code instead simply becomes
  part of the surrounding program.

Returning `Meta.parse(Permutation, str)` is enough.

2022-05-01 21:22 UTC, kalmarek commented
@fvanmaele great job! If this is your first serious coding session with julia I'm impressed ;)

2022-05-02 07:02 UTC, fvanmaele commented on test/permutations.jl
> +# (cf. TEMPLATE_TEST_CASE in Catch2)
Thanks! I didn't know looping over types `for P in [Permutation, CyclePermutation]` was possible.

2022-05-02 07:03 UTC, fvanmaele commented on test/permutations.jl
> +    # @test_throws Meta.ParseError perm"(2,3,1)⋅(4,5)" # this or (2,3,1)∗(4,5) is arguably also a valid case
Makes sense. When testing `string_to_cycles`, everything works as expected.

2022-05-02 07:24 UTC, fvanmaele commented on src/permutations.jl
> +    return deg
```julia
deg = 1
if length(σ.cycles) > 1
    deg = mapreduce(maximum, max, σ.cycles)
return deg
```
or with a ternary
```julia
return length(σ.cycles) > 1 ? mapreduce(maximum, max, σ.cycles) : 1
```
I tried to use `mapreduce(maximum, max, σ.cycles; init=1)` but the `init` only applies to the reduced collection, it doesn't work if the initial collection is empty:
```
ArgumentError: reducing over an empty collection is not allowed
```
Same for  `map(maximum, σ.cycles)`

2022-05-02 07:31 UTC, fvanmaele commented on src/permutations.jl
> +                σ_cat = vcat(σ_cat, c)
Noted. Then it makes sense there's no `push` or `append`, only `push!` and `append!`

2022-05-02 07:33 UTC, fvanmaele commented on src/permutations.jl
> +        σ = Permutation(v, check)
Hmm, I was using this as a shortcut because `cycle_decomposition` expects an `AbstractPermutation`. With what you said in https://github.com/kalmarek/CGT_UniHeidelberg_2022/pull/2#discussion_r862520634 I agree I should avoid it though. 🤔

2022-05-02 07:41 UTC, fvanmaele commented
Thanks for the comments. I've addressed some things with 872c8dda2834d9bd2beaadf5ce49e739b599786f

2022-05-02 07:42 UTC, fvanmaele commented on src/AbstractPermutations.jl
> +export AbstractPermutation, degree, cycle_decomposition
OK, I've removed `cycle_decomposition` from the `AbstractPermutations` exports.

2022-05-02 07:43 UTC, fvanmaele commented on src/permutations.jl
> +    return eval(Meta.parse(Permutation, str))
Good point

2022-05-02 07:59 UTC, fvanmaele commented on src/permutations.jl
> +    return deg
be62f4bd66193df387fc4a82546f77c890aebe83

2022-05-02 08:28 UTC, fvanmaele commented on src/permutations.jl
> +    images::Vector{Int}
With the assumption that the cycles are disjoint, something like this should work:
```julia
function map_cycles(cycles::AbstractVector{AbstractVector{<:Integer}}, i::Integer)
    # Go over each cycle until a match is found. This assumes the cycles
    # are disjoint.
    for cycle ∈ cycles
        for k in range(1, length(cycle)-1)
            if cycle[k] == i
                return cycle[k+1] # match found
            end
        end
        # handle periodic boundary
        if cycle[length(cycle)] == i
            return cycle[1]
        end
    end
end
```

2022-05-02 09:42 UTC, kalmarek commented on src/permutations.jl
> +    images::Vector{Int}
with the same assumption (disjointness of cycles) we can have
```julia
function (σ::CyclePermutation)(n::Integer)
    n > degree(σ) && return n
    for cycle in σ.cycles
        idx = findfirst(==(n), cycle)
        isnothing(idx) && continue
        next_idx = ifelse(idx < lenght(cycle), idx+1, 1)
        return cycle[next_idx]
    end
    return n # e.g. when we decide later not to store cycles of length 1
end
```

2022-05-02 09:42 UTC, kalmarek commented on src/permutations.jl
> +        σ = Permutation(v, check)
yes we should avoid using `cycle_decomposition` directly here.

2022-05-02 09:47 UTC, kalmarek commented on src/AbstractPermutations.jl
> +export AbstractPermutation, degree, cycle_decomposition
the export still appears to be there

2022-05-02 10:50 UTC, fvanmaele commented on src/AbstractPermutations.jl
> +export AbstractPermutation, degree, cycle_decomposition
Oops, second attempt with https://github.com/kalmarek/CGT_UniHeidelberg_2022/pull/2/commits/4b5d71fa1906f8f9cdecd388f8bff75a646e2e23

2022-05-02 10:53 UTC, fvanmaele commented on src/permutations.jl
> +        σ = Permutation(v, check)
Ok but doesn't that boil down to a specialization of `cycle_decomposition` for `AbstractVector{:<Integer}`? For example
```julia

# Ad-hoc implementation of cycle_decomposition() for vectors
# which follows indices until a cycle is encountered.
function AbstractPermutations.cycle_decomposition(images::AbstractVector{<:Integer})
    visited = falses(length(v))
    cycles = [Int[]]

    for i ∈ v
        if visited[i]
            continue
        end        
        cycle = Int[]
        i_cycle = i

        while images[i_cycle] != i
            push!(cycle, images[i_cycle])
            i_cycle = images[i_cycle]
        end

        # Only add non-trivial cycles (of length >=2). In
        # particular, if σ is the identity, cycles is empty.
        if length(cycle) >= 2
            push!(cycles, copy(cycle))
        end
    end
    return cycles
end
```
In that case what is the purpose of including `cycle_decomposition` in `AbstractPermutations`?

2022-05-02 10:56 UTC, kalmarek commented
> There was also a question in **Exercise 1**, about the behavior when multiplying `CyclePermutation` and `Permutation`. All I can think of is that this would be not type stable, in the sense that the output type depends on the order of the arguments.

It **is** type stable since the compiler can prove that the result of `τ*σ` will be of type `Permutation` without performing the computation (which is what type stability is about). The fact that it does depend on the order is well, a feature ;)

> That is, given the signature
> 
> ```julia
> Base.:(*)(σ::P, τ::AbstractPermutation) where P<:AbstractPermutation
> ```
> 
> and the inputs
> 
> ```
> σ = CyclePermutation([2,1])
> τ = Permutation([1,2,4,3])
> ```
> 
> we have `σ*τ = τ*σ` because these are disjoint cycles, but the output type differs:
> 
> ```
> julia> typeof(τ*σ)
> Permutation
> julia> typeof(σ*τ)
> CyclePermutation
> ```
> 
> I believe this follows from the fact that the constructor of `P` (the type of the first argument) is taken: in `Base.:(*)`
> 
> ```julia
> return P(img, false)
> ```

:ok_hand:

2022-05-02 11:00 UTC, kalmarek commented on src/permutations.jl
> +        σ = Permutation(v, check)
to have a uniform way of displaying of permutations. Which is either irrelevant, or very important depending on what is your point of view ;)

oh, and showing off the generality of `orbit` calculation ;)

2022-05-04 19:55 UTC, kalmarek commented
hmm I'm not sure if this was a mistake, it was definitely correct ;)

2022-05-04 19:56 UTC, kalmarek commented on src/permutations.jl
> +        deg = mapreduce(maximum, max, non_trivial_cycles; init=deg)
right now we trade going over cycles of length 1 for copying the whole cycle decomposition (`filter` is eager, hence copies the whole thing). We can leave it as is but then check on line 103 should be
```julia
if length(non_trivial_cycles) ≥ 1
```

2022-05-04 21:28 UTC, fvanmaele commented on src/permutations.jl
> +        deg = mapreduce(maximum, max, non_trivial_cycles; init=deg)
> right now we trade going over cycles of length 1 for copying the whole cycle decomposition 

Oops, this seems like a pretty bad tradeoff.

2022-05-04 21:32 UTC, fvanmaele commented
Okay, so my issue was that `CycleDecomposition2` of `[1,2,3]` resulted in `[1]`, `[2]` and `[3]` cycles, leading to a degree of 3 with `mapreduce`, whereas `CycleDecomposition` only has `[1]` for the same element. 

It took me a while to understand why: `cycle_decomposition(σ::Permutation)` loops over the degree, but `cycle_decomposition(σ::AbstractVector{:<Integer})` loops over the length `n`, resulting in these redundant cycles of length 1. 

I believe the proper fix would then be something like:
```julia
# Since we are looping over the length of the images, instead of
# over the degree, it is possible to have (several) cycles of
# length 1 (e.g. [1], [2], [3], ...). We could either accept
# that the identity has empty cycles, or only keep [1] as [2],
# ... are redundant.
if length(cycles) >= 2 || i == 1
    push!(cycles, copy(cycle))
end
```

2022-05-06 19:23 UTC, merged